export const MOCK_DOCTORS = [
  {
    id: "DOC-001",
    firstName: "Ramesh", lastName: "Kumar",
    designation: "Senior Veterinarian",
    specialization: "Small Animal Medicine",
    qualification: "MVSc",
    experience: "11",
    department: "OPD – General",
    employmentType: "Full-time",
    joiningDate: "2018-03-01",
    phone: "+91 98765 43210",
    email: "ramesh.kumar@vetcare.in",
    gender: "Male",
    status: "Active",
    rating: 4.8, reviews: 42,
    totalPatients: 348,
    appointmentsToday: 6,
    consultationFee: "600",
    availableDays: ["Mon","Tue","Wed","Thu","Fri","Sat"],
    languagesSpoken: ["English","Tamil","Hindi"],
    avatar: "R",
    regNumber: "TN-VCI-2013-00421",
  },
  {
    id: "DOC-002",
    firstName: "Priya", lastName: "Nair",
    designation: "Consultant Veterinarian",
    specialization: "Veterinary Surgery",
    qualification: "BVSc & AH",
    experience: "7",
    department: "OPD – Surgery",
    employmentType: "Full-time",
    joiningDate: "2020-07-15",
    phone: "+91 91234 56789",
    email: "priya.nair@vetcare.in",
    gender: "Female",
    status: "Active",
    rating: 4.9, reviews: 28,
    totalPatients: 214,
    appointmentsToday: 4,
    consultationFee: "800",
    availableDays: ["Mon","Tue","Wed","Thu","Fri"],
    languagesSpoken: ["English","Tamil","Malayalam"],
    avatar: "P",
    regNumber: "TN-VCI-2017-00892",
  },
  {
    id: "DOC-003",
    firstName: "Arun", lastName: "Selvam",
    designation: "Resident Veterinarian",
    specialization: "Avian Medicine",
    qualification: "BVSc",
    experience: "3",
    department: "OPD – General",
    employmentType: "Part-time",
    joiningDate: "2022-01-10",
    phone: "+91 97654 32109",
    email: "arun.selvam@vetcare.in",
    gender: "Male",
    status: "Active",
    rating: 4.5, reviews: 14,
    totalPatients: 89,
    appointmentsToday: 3,
    consultationFee: "400",
    availableDays: ["Mon","Wed","Fri","Sat"],
    languagesSpoken: ["English","Tamil"],
    avatar: "A",
    regNumber: "TN-VCI-2021-01234",
  },
  {
    id: "DOC-004",
    firstName: "Meena", lastName: "Pillai",
    designation: "Specialist Veterinarian",
    specialization: "Veterinary Dermatology",
    qualification: "MVSc",
    experience: "9",
    department: "OPD – Dermatology",
    employmentType: "Visiting / Consultant",
    joiningDate: "2019-06-01",
    phone: "+91 93456 78901",
    email: "meena.pillai@vetcare.in",
    gender: "Female",
    status: "Active",
    rating: 4.7, reviews: 33,
    totalPatients: 276,
    appointmentsToday: 5,
    consultationFee: "750",
    availableDays: ["Tue","Thu","Sat"],
    languagesSpoken: ["English","Malayalam","Tamil"],
    avatar: "M",
    regNumber: "TN-VCI-2015-00567",
  },
  {
    id: "DOC-005",
    firstName: "Karthik", lastName: "Rajan",
    designation: "Junior Veterinarian",
    specialization: "General Veterinary Practice",
    qualification: "BVSc & AH",
    experience: "2",
    department: "IPD – Inpatient Care",
    employmentType: "Full-time",
    joiningDate: "2023-03-20",
    phone: "+91 88765 43210",
    email: "karthik.rajan@vetcare.in",
    gender: "Male",
    status: "Active",
    rating: 4.3, reviews: 9,
    totalPatients: 61,
    appointmentsToday: 2,
    consultationFee: "350",
    availableDays: ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"],
    languagesSpoken: ["Tamil","English"],
    avatar: "K",
    regNumber: "TN-VCI-2023-02145",
  },
  {
    id: "DOC-006",
    firstName: "Divya", lastName: "Krishnamurthy",
    designation: "Veterinary Surgeon",
    specialization: "Veterinary Dentistry",
    qualification: "MVSc",
    experience: "6",
    department: "OPD – Dentistry",
    employmentType: "Full-time",
    joiningDate: "2021-09-01",
    phone: "+91 99876 54321",
    email: "divya.k@vetcare.in",
    gender: "Female",
    status: "Inactive",
    rating: 4.6, reviews: 21,
    totalPatients: 158,
    appointmentsToday: 0,
    consultationFee: "700",
    availableDays: ["Mon","Tue","Wed","Thu","Fri"],
    languagesSpoken: ["English","Tamil","Kannada"],
    avatar: "D",
    regNumber: "TN-VCI-2018-00734",
  },
  {
    id: "DOC-007",
    firstName: "Suresh", lastName: "Babu",
    designation: "Chief Veterinary Officer",
    specialization: "Exotic Animal Medicine",
    qualification: "PhD (Veterinary)",
    experience: "18",
    department: "ICU / Critical Care",
    employmentType: "Full-time",
    joiningDate: "2010-04-15",
    phone: "+91 87654 32109",
    email: "suresh.babu@vetcare.in",
    gender: "Male",
    status: "Active",
    rating: 5.0, reviews: 67,
    totalPatients: 892,
    appointmentsToday: 8,
    consultationFee: "1200",
    availableDays: ["Mon","Tue","Wed","Thu","Fri"],
    languagesSpoken: ["English","Tamil","Hindi","Telugu"],
    avatar: "S",
    regNumber: "TN-VCI-2006-00089",
  },
  {
    id: "DOC-008",
    firstName: "Ananya", lastName: "Menon",
    designation: "Resident Veterinarian",
    specialization: "Veterinary Radiology",
    qualification: "MVSc",
    experience: "4",
    department: "Diagnostics & Lab",
    employmentType: "Full-time",
    joiningDate: "2022-08-01",
    phone: "+91 96543 21098",
    email: "ananya.menon@vetcare.in",
    gender: "Female",
    status: "Active",
    rating: 4.4, reviews: 12,
    totalPatients: 124,
    appointmentsToday: 3,
    consultationFee: "500",
    availableDays: ["Mon","Tue","Wed","Thu","Fri","Sat"],
    languagesSpoken: ["English","Malayalam"],
    avatar: "A",
    regNumber: "TN-VCI-2020-01567",
  },
];

export const SPECIALIZATION_FILTER = [
  "All",
  "Small Animal Medicine",
  "Veterinary Surgery",
  "Avian Medicine",
  "Veterinary Dermatology",
  "General Veterinary Practice",
  "Veterinary Dentistry",
  "Exotic Animal Medicine",
  "Veterinary Radiology",
];

export const DEPARTMENT_FILTER = [
  "All",
  "OPD – General",
  "OPD – Surgery",
  "OPD – Dermatology",
  "OPD – Dentistry",
  "IPD – Inpatient Care",
  "ICU / Critical Care",
  "Diagnostics & Lab",
];

export const STATUS_FILTER    = ["All", "Active", "Inactive"];
export const EMPLOYMENT_FILTER = ["All", "Full-time", "Part-time", "Visiting / Consultant", "Contract"];

export const SORT_OPTIONS = [
  { value: "name_asc",    label: "Name A–Z"       },
  { value: "name_desc",   label: "Name Z–A"       },
  { value: "experience",  label: "Most Experienced"},
  { value: "rating",      label: "Highest Rated"  },
  { value: "patients",    label: "Most Patients"  },
  { value: "recent",      label: "Recently Joined"},
];