export const MOCK_DOCTOR = {
  id:                  "DOC-001",
  firstName:           "Ramesh",
  lastName:            "Kumar",
  designation:         "Senior Veterinarian",
  specialization:      "Small Animal Medicine",
  subSpecialization:   "Feline Cardiology",
  qualification:       "MVSc",
  experience:          "11",
  regNumber:           "TN-VCI-2013-00421",
  regCouncil:          "Tamil Nadu Veterinary Council",
  regYear:             "2013",
  gender:              "Male",
  dob:                 "1985-06-14",
  phone:               "+91 98765 43210",
  altPhone:            "+91 91234 56789",
  email:               "ramesh.kumar@vetcare.in",
  addressLine1:        "24, Anna Nagar West",
  city:                "Chennai",
  state:               "Tamil Nadu",
  pincode:             "600040",
  department:          "OPD – General",
  employmentType:      "Full-time",
  joiningDate:         "2018-03-01",
  consultationFee:     "600",
  followUpFee:         "300",
  emergencyFee:        "1500",
  consultationDuration:"20",
  availableDays:       ["Mon","Tue","Wed","Thu","Fri","Sat"],
  morningStart:        "09:00",
  morningEnd:          "13:00",
  eveningStart:        "17:00",
  eveningEnd:          "21:00",
  lunchBreak:          true,
  languagesSpoken:     ["English","Tamil","Hindi"],
  bio:                 "Dr. Ramesh Kumar is a compassionate and highly experienced veterinarian with over 11 years of clinical practice. He specialises in small animal medicine with a focus on feline cardiology and internal medicine. Known for his gentle approach with animals and clear communication with pet owners.",
  achievements:        "Best Veterinarian Award – VetCare 2022 · Published research on feline HCM in Indian Journal of Veterinary Science 2020 · Speaker at National Veterinary Congress 2021",
  status:              "Active",
  totalPatients:       348,
  appointmentsToday:   6,
  rating:              4.8,
  reviews:             42,
};

export const MOCK_RECENT_PATIENTS = [
  { id:"VET-001", name:"Bruno",    species:"🐕", breed:"Labrador",  owner:"Rahul Sharma",  date:"2025-03-28", reason:"Vaccination"        },
  { id:"VET-006", name:"Luna",     species:"🐈", breed:"Siamese",   owner:"Kavitha Rajan", date:"2025-03-27", reason:"Routine Checkup"    },
  { id:"VET-004", name:"Rocky",    species:"🐕", breed:"G. Shepherd",owner:"Deepa Menon",  date:"2025-03-26", reason:"Hip Dysplasia Follow-up" },
  { id:"VET-002", name:"Whiskers", species:"🐈", breed:"Persian",   owner:"Priya Nair",    date:"2025-03-25", reason:"Asthma Treatment"   },
  { id:"VET-007", name:"Tiger",    species:"🐕", breed:"Pariah",    owner:"Murugan Pillai",date:"2025-03-24", reason:"Arthritis Review"   },
];

export const MOCK_UPCOMING = [
  { id:"APT-101", petName:"Coco",    owner:"Suresh Babu",   time:"09:00", type:"OPD"       },
  { id:"APT-102", petName:"Bruno",   owner:"Rahul Sharma",  time:"09:20", type:"Follow-up" },
  { id:"APT-103", petName:"Goldie",  owner:"Ananya K",      time:"09:40", type:"OPD"       },
  { id:"APT-104", petName:"Mango",   owner:"Arun Kumar",    time:"10:00", type:"Vaccination"},
  { id:"APT-105", petName:"Rocky",   owner:"Deepa Menon",   time:"10:20", type:"Surgery"   },
  { id:"APT-106", petName:"Luna",    owner:"Kavitha Rajan", time:"10:40", type:"OPD"       },
];