export const MOCK_PATIENTS = [
  {
    id: "VET-001",
    name: "Bruno",
    species: "Dog",
    emoji: "🐕",
    breed: "Labrador Retriever",
    age: "3 Years",
    gender: "Male",
    color: "Golden",
    microchipId: "982000411234567",
    ownerName: "Rahul Sharma",
    ownerContact: "+91 98765 43210",
    ownerEmail: "rahul.sharma@email.com",
    city: "Chennai",
    vaccinated: "Yes",
    neutered: "Yes",
    lastVisit: "2025-03-10",
    nextDue: "2025-09-10",
    bloodGroup: "DEA 1.1+",
    conditions: "None",
    status: "Active",
    registeredOn: "2024-01-15",
    weight: "28 kg",
  },
  {
    id: "VET-002",
    name: "Whiskers",
    species: "Cat",
    emoji: "🐈",
    breed: "Persian",
    age: "5 Years",
    gender: "Female",
    color: "White",
    microchipId: "982000411234568",
    ownerName: "Priya Nair",
    ownerContact: "+91 91234 56789",
    ownerEmail: "priya.nair@email.com",
    city: "Chennai",
    vaccinated: "Yes",
    neutered: "Yes",
    lastVisit: "2025-02-20",
    nextDue: "2025-08-20",
    bloodGroup: "Type A",
    conditions: "Asthma",
    status: "Active",
    registeredOn: "2023-06-10",
    weight: "4 kg",
  },
  {
    id: "VET-003",
    name: "Mango",
    species: "Bird",
    emoji: "🦜",
    breed: "African Grey",
    age: "2 Years",
    gender: "Unknown",
    color: "Grey",
    microchipId: "",
    ownerName: "Arun Kumar",
    ownerContact: "+91 97654 32109",
    ownerEmail: "",
    city: "Coimbatore",
    vaccinated: "Partial",
    neutered: "Unknown",
    lastVisit: "2025-01-05",
    nextDue: "2025-07-05",
    bloodGroup: "Unknown",
    conditions: "None",
    status: "Active",
    registeredOn: "2024-03-22",
    weight: "0.4 kg",
  },
  {
    id: "VET-004",
    name: "Rocky",
    species: "Dog",
    emoji: "🐕",
    breed: "German Shepherd",
    age: "6 Years",
    gender: "Male",
    color: "Black & Tan",
    microchipId: "982000411234570",
    ownerName: "Deepa Menon",
    ownerContact: "+91 93456 78901",
    ownerEmail: "deepa.menon@email.com",
    city: "Madurai",
    vaccinated: "Yes",
    neutered: "No",
    lastVisit: "2025-03-18",
    nextDue: "2025-09-18",
    bloodGroup: "DEA 1.1-",
    conditions: "Hip Dysplasia",
    status: "Active",
    registeredOn: "2022-11-05",
    weight: "35 kg",
  },
  {
    id: "VET-005",
    name: "Coco",
    species: "Rabbit",
    emoji: "🐇",
    breed: "Holland Lop",
    age: "1 Year",
    gender: "Female",
    color: "Brown & White",
    microchipId: "",
    ownerName: "Suresh Babu",
    ownerContact: "+91 88765 43210",
    ownerEmail: "suresh.babu@email.com",
    city: "Chennai",
    vaccinated: "No",
    neutered: "No",
    lastVisit: "2025-02-01",
    nextDue: "2025-06-01",
    bloodGroup: "Unknown",
    conditions: "None",
    status: "Inactive",
    registeredOn: "2024-08-30",
    weight: "2 kg",
  },
  {
    id: "VET-006",
    name: "Luna",
    species: "Cat",
    emoji: "🐈",
    breed: "Siamese",
    age: "4 Years",
    gender: "Female",
    color: "Cream & Brown",
    microchipId: "982000411234572",
    ownerName: "Kavitha Rajan",
    ownerContact: "+91 99876 54321",
    ownerEmail: "kavitha.rajan@email.com",
    city: "Trichy",
    vaccinated: "Yes",
    neutered: "Yes",
    lastVisit: "2025-03-25",
    nextDue: "2025-09-25",
    bloodGroup: "Type B",
    conditions: "Diabetes",
    status: "Active",
    registeredOn: "2023-02-14",
    weight: "3.8 kg",
  },
  {
    id: "VET-007",
    name: "Tiger",
    species: "Dog",
    emoji: "🐕",
    breed: "Indian Pariah",
    age: "8 Years",
    gender: "Male",
    color: "Tan",
    microchipId: "982000411234573",
    ownerName: "Murugan Pillai",
    ownerContact: "+91 87654 32109",
    ownerEmail: "",
    city: "Chennai",
    vaccinated: "Partial",
    neutered: "Yes",
    lastVisit: "2024-12-10",
    nextDue: "2025-06-10",
    bloodGroup: "DEA 1.1+",
    conditions: "Arthritis",
    status: "Active",
    registeredOn: "2021-07-20",
    weight: "22 kg",
  },
  {
    id: "VET-008",
    name: "Goldie",
    species: "Fish",
    emoji: "🐟",
    breed: "Goldfish",
    age: "6 Months",
    gender: "Unknown",
    color: "Orange",
    microchipId: "",
    ownerName: "Ananya Krishnan",
    ownerContact: "+91 96543 21098",
    ownerEmail: "ananya.k@email.com",
    city: "Chennai",
    vaccinated: "No",
    neutered: "Unknown",
    lastVisit: "2025-03-01",
    nextDue: "",
    bloodGroup: "Unknown",
    conditions: "None",
    status: "Active",
    registeredOn: "2024-11-15",
    weight: "0.05 kg",
  },
];

export const SPECIES_FILTER = ["All", "Dog", "Cat", "Bird", "Rabbit", "Fish", "Hamster", "Reptile", "Other"];
export const STATUS_FILTER  = ["All", "Active", "Inactive"];
export const SORT_OPTIONS   = [
  { value: "name_asc",   label: "Name A–Z"        },
  { value: "name_desc",  label: "Name Z–A"        },
  { value: "recent",     label: "Recently Added"  },
  { value: "visit",      label: "Last Visit"      },
];